#! /bin/sh

FIRST_DESK=1
#REMAINING_DESKS="$(seq 2 9) 0"
REMAINING_DESKS="2 3 0"
FIRST_DESK_EXTERNAL=main
REMAINING_DESKS_EXTERNAL="www irc four five"

bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS
bspc monitor -p 40 0 0 0

if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
echo "No monitor connected"
else
bspc monitor -f next
bspc desktop Desktop02 -n $FIRST_DESK_EXTERNAL
bspc monitor -a $REMAINING_DESKS_EXTERNAL
bspc monitor -p 40 0 0 0
fi

bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          7
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config focused_border_color #171717
#bspc config normal_border_color #322d29

bspc rule -a Gimp --floating
bspc rule -a mupdf --floating

~/.config/bspwm/bspanel.sh 2> /dev/null
~/.config/bspwm/bspanel2.sh 2> /dev/null