#!/bin/bash
# --------------------------------------------------
#                          HERBSTLUFT WM CONFIG FILE
# --------------------------------------------------
# 
#  ██                     ██                ██    ██           ████   ██  
# ░██                    ░██               ░██   ░██          ░██░   ░██  
# ░██       █████  ██████░██       ██████ ██████ ░██ ██   ██ ██████ ██████
# ░██████  ██░░░██░░██░░█░██████  ██░░░░ ░░░██░  ░██░██  ░██░░░██░ ░░░██░ 
# ░██░░░██░███████ ░██ ░ ░██░░░██░░█████   ░██   ░██░██  ░██  ░██    ░██  
# ░██  ░██░██░░░░  ░██   ░██  ░██ ░░░░░██  ░██   ░██░██  ░██  ░██    ░██  
# ░██  ░██░░██████░███   ░██████  ██████   ░░██  ███░░██████  ░██    ░░██ 
# ░░   ░░  ░░░░░░ ░░░    ░░░░░   ░░░░░░     ░░  ░░░  ░░░░░░   ░░      ░░  
hc() {
    herbstclient "$@"
}
hc emit_hook reload
# KEYBINDINGS
hc keyunbind --all
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-w spawn $HOME/bin/locker.sh

#mon_width=$(herbstclient monitor_rect | awk '{ print $3}')
#mon_height=$(herbstclient monitor_rect | awk '{ print $4}')
#dm_x=$(($mon_width / 2 - 160))
#dm_y=$(($mon_height/2))
#hc keybind $Mod-p spawn dmenu_run -dim 0.3 -w 320 -h 20 -l 5 -i -p "Run >>" -x $dm_x -y $dm_y -sb '#FF590F' -nb '#262626' -fn 'pragmata-8-'

hc keybind $Mod-p spawn dmenu_run -b -l 3 -i -p ">" -sb '#FF590F' -nb '#262626' -fn 'pragmata-8-'
hc keybind XF86AudioLowerVolume spawn $HOME/bin/sound.sh down
hc keybind XF86AudioRaiseVolume spawn $HOME/bin/sound.sh up
hc keybind XF86AudioMute        spawn $HOME/bin/sound.sh mute
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-r remove # remove frame 
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-t pseudotile toggle
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
# TAGS
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
# COLORS AND BORDERS
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#303030'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#303030'
hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_padding 1
hc set always_show_frame 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set window_border_width 3
hc set window_border_inner_width -1
hc set window_border_normal_color '#292929'
hc set window_border_active_color '#111111'
hc set window_gap 10
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1
hc set swap_monitors_to_get_tag 0
# RULES
hc unrule -F
hc rule focus=off # normally do not focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient set tree_style '╾│ ├└╼─┐'
# MONITORS
# hc set_monitors 1280x800+0+0 1920x1080+1280+0
# hc detect_monitors
hc remove_monitor 1
hc move_monitor 0 1280x800+0+0
hc use "${TAG_NAMES[0]}"
hc add_monitor 1920x1080+1280+0 "${TAG_NAMES[1]}"
hc pad 0 40 0 0 0
#hc pad 0 40 0 25
hc pad 1 40 0 25
hc unlock
# LAUNCH PAD
~/.config/herbstluftwm/bspanel.sh &
~/.config/herbstluftwm/bspanel2.sh &
compton -D1 -cGfb
conky -q
